# Generated by Django 4.2.3 on 2023-07-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0003_autor_livro"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name": "Autor", "verbose_name_plural": "Autores"},
        ),
        migrations.AddField(
            model_name="livro",
            name="autores",
            field=models.ManyToManyField(related_name="livros", to="livraria.autor"),
        ),
    ]
